---
- name: Set Ip 
  hosts: all
  gather_facts: no

  tasks:
    - name: Dat ip cho cong fastEthernet0/1
      ios_l3_interface:
        name: GigabitEthernet0/1
        ipv4: 192.168.1.1/24

    - name: Show ip
      ios_command:
        commands:
         - show ip int bri
      register: show_ip
