---
- name: Set Ip Loobpack
  hosts: all
  gather_facts: no

  tasks:
    - name: Set loopback IPv4 address
      ios_l3_interface:
        name: loopback 1
        ipv4: 10.0.1.1/24

    - name: Set loopback IPv4 address
      ios_l3_interface:
        name: loopback 2
        ipv4: 10.0.2.2/24
        
    - name: Show ip
      ios_command:
        commands:
         - show ip int bri
      register: show_ip
